//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.ISS16
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Условие.
    /// </summary>
    // *** Start programmer edit section *** (Условие CustomAttributes)

    // *** End programmer edit section *** (Условие CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("УсловиеE", new string[] {
            "Нименование as \'Нименование\'",
            "НомерПоддержки as \'Номер поддержки\'"})]
    [View("УсловиеL", new string[] {
            "Нименование as \'Нименование\'",
            "НомерПоддержки as \'Номер поддержки\'"})]
    public class Условие : ICSSoft.STORMNET.DataObject
    {
        
        private string fНименование;
        
        private string fНомерПоддержки;
        
        // *** Start programmer edit section *** (Условие CustomMembers)

        // *** End programmer edit section *** (Условие CustomMembers)

        
        /// <summary>
        /// Нименование.
        /// </summary>
        // *** Start programmer edit section *** (Условие.Нименование CustomAttributes)

        // *** End programmer edit section *** (Условие.Нименование CustomAttributes)
        [StrLen(255)]
        public virtual string Нименование
        {
            get
            {
                // *** Start programmer edit section *** (Условие.Нименование Get start)

                // *** End programmer edit section *** (Условие.Нименование Get start)
                string result = this.fНименование;
                // *** Start programmer edit section *** (Условие.Нименование Get end)

                // *** End programmer edit section *** (Условие.Нименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Условие.Нименование Set start)

                // *** End programmer edit section *** (Условие.Нименование Set start)
                this.fНименование = value;
                // *** Start programmer edit section *** (Условие.Нименование Set end)

                // *** End programmer edit section *** (Условие.Нименование Set end)
            }
        }
        
        /// <summary>
        /// НомерПоддержки.
        /// </summary>
        // *** Start programmer edit section *** (Условие.НомерПоддержки CustomAttributes)

        // *** End programmer edit section *** (Условие.НомерПоддержки CustomAttributes)
        [StrLen(255)]
        public virtual string НомерПоддержки
        {
            get
            {
                // *** Start programmer edit section *** (Условие.НомерПоддержки Get start)

                // *** End programmer edit section *** (Условие.НомерПоддержки Get start)
                string result = this.fНомерПоддержки;
                // *** Start programmer edit section *** (Условие.НомерПоддержки Get end)

                // *** End programmer edit section *** (Условие.НомерПоддержки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Условие.НомерПоддержки Set start)

                // *** End programmer edit section *** (Условие.НомерПоддержки Set start)
                this.fНомерПоддержки = value;
                // *** Start programmer edit section *** (Условие.НомерПоддержки Set end)

                // *** End programmer edit section *** (Условие.НомерПоддержки Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "УсловиеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УсловиеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УсловиеE", typeof(IIS.ISS16.Условие));
                }
            }
            
            /// <summary>
            /// "УсловиеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УсловиеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УсловиеL", typeof(IIS.ISS16.Условие));
                }
            }
        }
    }
}
